package main;

public enum Country {
	ARGENTINA, AUSTRALIA, AUSTRIA, AZERBAIJAN, BAHRAIN, BELGIUM, BRAZIL, CANADA, CHILE, CHINA, COLOMBIA, CROATIA, CZECHIA, FRANCE, GEORGIA, GERMANY, GREAT_BRITAIN, HUNGARY, INDIA, INDONESIA, ITALY, JAPAN, KUWAIT, MALAYSIA, MEXICO, MONACO, MOROCCO, NEW_ZEALAND, NORWAY, PORTUGAL, QATAR, ROMANIA, RUSSIA, SAUDI_ARABIA, SENEGAL, SINGAPORE, SLOVAKIA, SOUTH_AFRICA, SOUTH_KOREA, SPAIN, SWEDEN, TAIWAN, THAILAND, THE_NETHERLANDS, TURKEY, UNITED_ARAB_EMIRATES, UNITED_STATES, URUGUAY, VIETNAM
}
