package main;

public enum Country {
	AUSTRALIA, BAHRAIN, CHINA, AZERBAIJAN, SPAIN, MONACO, CANADA, FRANCE, GREAT_BRITAIN, AUSTRIA, GERMANY, HUNGARY, BELGIUM, ITALY, SINGAPORE, JAPAN, MEXICO, UNITED_STATES, BRAZIL, UNITED_ARAB_EMIRATES
}
