/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui;

import grandprixworld.gamedata.CurrentGameData;
import java.awt.CardLayout;

/**
 *
 * @author jdb50
 */
public class FullGame extends javax.swing.JPanel {

    static CardLayout screens;
    public static CurrentGameData data;
    
    /**
     * Creates new form FullGame
     */
    public FullGame() {
        initData();
        initComponents();
        screens = (CardLayout) pnlAll.getLayout();
        screens.show(pnlAll, "mainmenu");
    }

    public static void gameStart() {
        gameScreen = new grandprixworld.gui.GameScreen();
        pnlAll.add(gameScreen, "game");
        screens.show(pnlAll, "game");
    }
    
    public static void raceStart() {
        raceWeekend = new grandprixworld.gui.raceWeekend.rwAll();
        pnlAll.add(raceWeekend, "race");
        screens.show(pnlAll, "race");
        gameScreen.removeAll();
        gameScreen = null;
    }
    
    public static void exitRaceWeekend() {
        raceWeekend.removeAll();
        raceWeekend = null;
        gameScreen = new grandprixworld.gui.GameScreen();
        pnlAll.add(gameScreen, "game");
        screens.show(pnlAll, "game");
    }
    
    public static void returnToGame() {
        raceWeekend.removeAll();
        raceWeekend = null;
        gameScreen = new grandprixworld.gui.GameScreen();
        pnlAll.add(gameScreen, "game");
        screens.show(pnlAll, "game");
    }
    
    private void initData() {
        data = new CurrentGameData(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        mainMenu1 = new grandprixworld.gui.MainMenu();

        setBackground(new java.awt.Color(64, 64, 64));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));

        pnlAll.setOpaque(false);
        pnlAll.setLayout(new java.awt.CardLayout());
        pnlAll.add(mainMenu1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, 1434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static grandprixworld.gui.GameScreen gameScreen;
    private static grandprixworld.gui.raceWeekend.rwAll raceWeekend;
    //private static grandprixworld.gui.raceWeekend.rwTemp raceWeekend;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private grandprixworld.gui.MainMenu mainMenu1;
    private static javax.swing.JPanel pnlAll;
    // End of variables declaration//GEN-END:variables
}
