/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui;

import grandprixworld.gamedata.CurrentGameData;
import grandprixworld.gamedata.Team;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;


/**
 *
 * @author jdb50
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    CardLayout cards;
    String name;
    int currentCard;
    String team;
    
    public MainMenu() {
        initComponents();
        initOther();
        cards = (CardLayout) (pnlCentre.getLayout());
        cards.show(pnlCentre, "home");
        btnAdvance.setVisible(false);
        currentCard = 1;
    }

    private void initOther() {
        teamSelect = new grandprixworld.gui.TeamSelect();
        pnlCentre.add(teamSelect, "SelectTeam");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblToolTip = new javax.swing.JLabel();
        btnStart = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnQuit = new javax.swing.JLabel();
        btnAdvance = new javax.swing.JLabel();
        imgTeam = new javax.swing.JLabel();
        lblTeam = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        pnlCentre = new javax.swing.JPanel();
        nameEntry = new grandprixworld.gui.NameEntry();
        saveGame = new grandprixworld.gui.SaveGame();
        homePage = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));
        setPreferredSize(new java.awt.Dimension(1440, 800));

        lblToolTip.setBackground(new java.awt.Color(100, 100, 100));
        lblToolTip.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lblToolTip.setForeground(new java.awt.Color(255, 255, 255));
        lblToolTip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/contextbanner.png"))); // NOI18N
        lblToolTip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/start.png"))); // NOI18N
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/f1 logo.png"))); // NOI18N

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quit.png"))); // NOI18N
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });

        btnAdvance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/advanceALT.png"))); // NOI18N
        btnAdvance.setText("jLabel6");
        btnAdvance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdvanceMouseClicked(evt);
            }
        });

        imgTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/teamplain.png"))); // NOI18N
        imgTeam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTeam.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lblTeam.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label.png"))); // NOI18N
        lblTeam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMoney.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lblMoney.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label.png"))); // NOI18N
        lblMoney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblStart.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lblStart.setForeground(new java.awt.Color(255, 255, 255));
        lblStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStart.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        pnlCentre.setBackground(new java.awt.Color(88, 103, 108));
        pnlCentre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        pnlCentre.setLayout(new java.awt.CardLayout());
        pnlCentre.add(nameEntry, "EnterName");
        pnlCentre.add(saveGame, "SaveGame");

        homePage.setOpaque(false);

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        pnlCentre.add(homePage, "home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMoney))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuit)
                            .addComponent(btnStart)
                            .addComponent(btnAbout))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblToolTip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(imgTeam)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdvance)
                        .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        cards.show(pnlCentre, "EnterName");
        btnAdvance.setVisible(true);
        currentCard = 2;
        lblToolTip.setText("Start a new game");
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        cards.show(pnlCentre, "SaveGame");
        btnAdvance.setVisible(false);
        currentCard = 5;
        lblToolTip.setText("Game Options");
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnQuitMouseClicked

    private void btnAdvanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdvanceMouseClicked
        if (currentCard == 2 && !(nameEntry.txtName.getText().isEmpty())) {
            name = nameEntry.txtName.getText();
            cards.show(pnlCentre, "SelectTeam");
            currentCard = 3;
            lblToolTip.setText("Select a team");
        } else if (currentCard == 3) {
            
            team = teamSelect.teamsTabs.getTitleAt(teamSelect.teamsTabs.getSelectedIndex());
            FullGame.data.teams.get(FullGame.data.findTeamIndexByName(team)).principal = name;
            FullGame.data.teams.get(FullGame.data.findTeamIndexByName(team)).isPlayer = true;
            FullGame.gameStart();
        }
    }//GEN-LAST:event_btnAdvanceMouseClicked
    
    private grandprixworld.gui.TeamSelect teamSelect;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnAdvance;
    private javax.swing.JLabel btnQuit;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel btnStart;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel imgTeam;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lblToolTip;
    private grandprixworld.gui.NameEntry nameEntry;
    private javax.swing.JPanel pnlCentre;
    private grandprixworld.gui.SaveGame saveGame;
    // End of variables declaration//GEN-END:variables
   
    @Override
    public void paintComponent(Graphics g) {
		super.paintComponent(g);
		Graphics2D g2d = (Graphics2D) g;
		g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
		Color c1 = Color.BLACK;
		Color c2 = new Color(88,103,108);
		GradientPaint gp = new GradientPaint(0, 0, c1, getWidth(), 0, c2);
		g2d.setPaint(gp);
		g2d.fillRect(0, 0, getWidth(), getHeight());
                
	}
}
