/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui;

/**
 *
 * @author Josh Brookes
 */
public class SaveGame extends javax.swing.JPanel {

    /**
     * Creates new form SaveGame
     */
    public SaveGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveGames = new javax.swing.JTabbedPane();
        pnlSave1 = new javax.swing.JPanel();
        pnlSave2 = new javax.swing.JPanel();
        pnlSave3 = new javax.swing.JPanel();
        pnlSave4 = new javax.swing.JPanel();
        pnlSave5 = new javax.swing.JPanel();
        pnlSave6 = new javax.swing.JPanel();
        pnlSave7 = new javax.swing.JPanel();
        pnlSave8 = new javax.swing.JPanel();
        pnlSave9 = new javax.swing.JPanel();
        pnlSave10 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(88, 103, 108));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setPreferredSize(new java.awt.Dimension(1100, 550));

        saveGames.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        saveGames.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        saveGames.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        pnlSave1.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave1Layout = new javax.swing.GroupLayout(pnlSave1);
        pnlSave1.setLayout(pnlSave1Layout);
        pnlSave1Layout.setHorizontalGroup(
            pnlSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave1Layout.setVerticalGroup(
            pnlSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save01", pnlSave1);

        pnlSave2.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave2Layout = new javax.swing.GroupLayout(pnlSave2);
        pnlSave2.setLayout(pnlSave2Layout);
        pnlSave2Layout.setHorizontalGroup(
            pnlSave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave2Layout.setVerticalGroup(
            pnlSave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save02", pnlSave2);

        pnlSave3.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave3Layout = new javax.swing.GroupLayout(pnlSave3);
        pnlSave3.setLayout(pnlSave3Layout);
        pnlSave3Layout.setHorizontalGroup(
            pnlSave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave3Layout.setVerticalGroup(
            pnlSave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save03", pnlSave3);

        pnlSave4.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave4Layout = new javax.swing.GroupLayout(pnlSave4);
        pnlSave4.setLayout(pnlSave4Layout);
        pnlSave4Layout.setHorizontalGroup(
            pnlSave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave4Layout.setVerticalGroup(
            pnlSave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save04", pnlSave4);

        pnlSave5.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave5Layout = new javax.swing.GroupLayout(pnlSave5);
        pnlSave5.setLayout(pnlSave5Layout);
        pnlSave5Layout.setHorizontalGroup(
            pnlSave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave5Layout.setVerticalGroup(
            pnlSave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save05", pnlSave5);

        pnlSave6.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave6Layout = new javax.swing.GroupLayout(pnlSave6);
        pnlSave6.setLayout(pnlSave6Layout);
        pnlSave6Layout.setHorizontalGroup(
            pnlSave6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave6Layout.setVerticalGroup(
            pnlSave6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save06", pnlSave6);

        pnlSave7.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave7Layout = new javax.swing.GroupLayout(pnlSave7);
        pnlSave7.setLayout(pnlSave7Layout);
        pnlSave7Layout.setHorizontalGroup(
            pnlSave7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave7Layout.setVerticalGroup(
            pnlSave7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save07", pnlSave7);

        pnlSave8.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave8Layout = new javax.swing.GroupLayout(pnlSave8);
        pnlSave8.setLayout(pnlSave8Layout);
        pnlSave8Layout.setHorizontalGroup(
            pnlSave8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave8Layout.setVerticalGroup(
            pnlSave8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save08", pnlSave8);

        pnlSave9.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave9Layout = new javax.swing.GroupLayout(pnlSave9);
        pnlSave9.setLayout(pnlSave9Layout);
        pnlSave9Layout.setHorizontalGroup(
            pnlSave9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave9Layout.setVerticalGroup(
            pnlSave9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save09", pnlSave9);

        pnlSave10.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlSave10Layout = new javax.swing.GroupLayout(pnlSave10);
        pnlSave10.setLayout(pnlSave10Layout);
        pnlSave10Layout.setHorizontalGroup(
            pnlSave10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        pnlSave10Layout.setVerticalGroup(
            pnlSave10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        saveGames.addTab("Save10", pnlSave10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveGames, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveGames)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

/*
    private void initComponents() {
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jTabbedPane13 = new javax.swing.JTabbedPane();
        jTabbedPane14 = new javax.swing.JTabbedPane();
        jTabbedPane15 = new javax.swing.JTabbedPane();
        jTabbedPane16 = new javax.swing.JTabbedPane();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        jTabbedPane19 = new javax.swing.JTabbedPane();
        jTabbedPane20 = new javax.swing.JTabbedPane();
        jTabbedPane21 = new javax.swing.JTabbedPane();
        jTabbedPane22 = new javax.swing.JTabbedPane();
        
        setBackground(new java.awt.Color(64, 64, 64));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));

        jTabbedPane12.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane12.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane12.setName(""); // NOI18N

        jTabbedPane13.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane13.setOpaque(true);
        jTabbedPane12.addTab("Save01", jTabbedPane13);

        jTabbedPane14.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane14.setOpaque(true);
        jTabbedPane12.addTab("Save02", jTabbedPane14);

        jTabbedPane15.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane15.setOpaque(true);
        jTabbedPane12.addTab("Save03", jTabbedPane15);

        jTabbedPane16.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane16.setOpaque(true);
        jTabbedPane12.addTab("Save04", jTabbedPane16);

        jTabbedPane17.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane17.setOpaque(true);
        jTabbedPane12.addTab("Save05", jTabbedPane17);

        jTabbedPane18.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane18.setOpaque(true);
        jTabbedPane12.addTab("Save06", jTabbedPane18);

        jTabbedPane19.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane19.setOpaque(true);
        jTabbedPane12.addTab("Save07", jTabbedPane19);

        jTabbedPane20.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane20.setOpaque(true);
        jTabbedPane12.addTab("Save08", jTabbedPane20);

        jTabbedPane21.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane21.setOpaque(true);
        jTabbedPane12.addTab("Save09", jTabbedPane21);

        jTabbedPane22.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jTabbedPane22.setOpaque(true);
        jTabbedPane12.addTab("Save10", jTabbedPane22);

        javax.swing.GroupLayout pnlSaveGameLayout = new javax.swing.GroupLayout(this);
        setLayout(pnlSaveGameLayout);
        pnlSaveGameLayout.setHorizontalGroup(
            pnlSaveGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 1639, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSaveGameLayout.setVerticalGroup(
            pnlSaveGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
    }
    
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane13;
    private javax.swing.JTabbedPane jTabbedPane14;
    private javax.swing.JTabbedPane jTabbedPane15;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    private javax.swing.JTabbedPane jTabbedPane19;
    private javax.swing.JTabbedPane jTabbedPane20;
    private javax.swing.JTabbedPane jTabbedPane21;
    private javax.swing.JTabbedPane jTabbedPane22;
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlSave1;
    private javax.swing.JPanel pnlSave10;
    private javax.swing.JPanel pnlSave2;
    private javax.swing.JPanel pnlSave3;
    private javax.swing.JPanel pnlSave4;
    private javax.swing.JPanel pnlSave5;
    private javax.swing.JPanel pnlSave6;
    private javax.swing.JPanel pnlSave7;
    private javax.swing.JPanel pnlSave8;
    private javax.swing.JPanel pnlSave9;
    private javax.swing.JTabbedPane saveGames;
    // End of variables declaration//GEN-END:variables
}
