/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui;

/**
 *
 * @author Josh Brookes
 */
public class TeamSelect extends javax.swing.JPanel {

    /**
     * Creates new form TeamSelect
     */
    public TeamSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamsTabs = new javax.swing.JTabbedPane();
        pnlMercedes = new javax.swing.JPanel();
        lblD1Merc = new javax.swing.JLabel();
        lblD1MercName = new javax.swing.JLabel();
        lblD2Merc = new javax.swing.JLabel();
        lblD2MercName = new javax.swing.JLabel();
        lblBalMercValue = new javax.swing.JLabel();
        lblBalMerc = new javax.swing.JLabel();
        pnlFerrari = new javax.swing.JPanel();
        lblD1Ferr = new javax.swing.JLabel();
        lblD1FerrName = new javax.swing.JLabel();
        lblD2Ferr = new javax.swing.JLabel();
        lblD2FerrName = new javax.swing.JLabel();
        lblBalFerrValue = new javax.swing.JLabel();
        lblBalFerr = new javax.swing.JLabel();
        pnlRedBull = new javax.swing.JPanel();
        lblD1RBR = new javax.swing.JLabel();
        lblD1RBRName = new javax.swing.JLabel();
        lblD2RBR = new javax.swing.JLabel();
        lblD2RBRName = new javax.swing.JLabel();
        lblBalRBRValue = new javax.swing.JLabel();
        lblBalRBR = new javax.swing.JLabel();
        pnlMcLaren = new javax.swing.JPanel();
        lblD1Mcl = new javax.swing.JLabel();
        lblD1MclName = new javax.swing.JLabel();
        lblD2Mcl = new javax.swing.JLabel();
        lblD2MclName = new javax.swing.JLabel();
        lblBalMclValue = new javax.swing.JLabel();
        lblBalMcl = new javax.swing.JLabel();
        pnlRenault = new javax.swing.JPanel();
        lblD1Ren = new javax.swing.JLabel();
        lblD1RenName = new javax.swing.JLabel();
        lblD2Ren = new javax.swing.JLabel();
        lblD2RenName = new javax.swing.JLabel();
        lblBalRenValue = new javax.swing.JLabel();
        lblBalRen = new javax.swing.JLabel();
        pnlToroRosso = new javax.swing.JPanel();
        lblD1STR = new javax.swing.JLabel();
        lblD1STRName = new javax.swing.JLabel();
        lblD2STR = new javax.swing.JLabel();
        lblD2STRName = new javax.swing.JLabel();
        lblBalSTRValue = new javax.swing.JLabel();
        lblBalSTR = new javax.swing.JLabel();
        pnlRacingPoint = new javax.swing.JPanel();
        lblD1RPt = new javax.swing.JLabel();
        lblD1RPtName = new javax.swing.JLabel();
        lblD2RPt = new javax.swing.JLabel();
        lblD2RPtName = new javax.swing.JLabel();
        lblBalRPtValue = new javax.swing.JLabel();
        lblBalRPt = new javax.swing.JLabel();
        pnlAlfaRomeo = new javax.swing.JPanel();
        lblD1Alfa = new javax.swing.JLabel();
        lblD1AlfaName = new javax.swing.JLabel();
        lblD2Alfa = new javax.swing.JLabel();
        lblD2AlfaName = new javax.swing.JLabel();
        lblBalAlfaValue = new javax.swing.JLabel();
        lblBalAlfa = new javax.swing.JLabel();
        pnlHaas = new javax.swing.JPanel();
        lblD1Haas = new javax.swing.JLabel();
        lblD1HaasName = new javax.swing.JLabel();
        lblD2Haas = new javax.swing.JLabel();
        lblD2HaasName = new javax.swing.JLabel();
        lblBalHaasValue = new javax.swing.JLabel();
        lblBalHaas = new javax.swing.JLabel();
        pnlWilliams = new javax.swing.JPanel();
        lblD1Will = new javax.swing.JLabel();
        lblD1WillName = new javax.swing.JLabel();
        lblD2Will = new javax.swing.JLabel();
        lblD2WillName = new javax.swing.JLabel();
        lblBalWillValue = new javax.swing.JLabel();
        lblBalWill = new javax.swing.JLabel();

        setBackground(new java.awt.Color(88, 103, 108));
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setPreferredSize(new java.awt.Dimension(1100, 550));

        teamsTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        teamsTabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        teamsTabs.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        pnlMercedes.setBackground(new java.awt.Color(88, 103, 108));
        pnlMercedes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 210, 190), 3));
        pnlMercedes.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Merc.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Merc.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Merc.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Merc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Merc.setText("Driver 1");
        lblD1Merc.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1Merc.setOpaque(true);

        lblD1MercName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1MercName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1MercName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1MercName.setText(FullGame.data.findTeamByName("Mercedes").driver1.fname + " " + FullGame.data.findTeamByName("Mercedes").driver1.lname);
        lblD1MercName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1MercName.setOpaque(true);

        lblD2Merc.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Merc.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Merc.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Merc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Merc.setText("Driver 2");
        lblD2Merc.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2Merc.setOpaque(true);

        lblD2MercName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2MercName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2MercName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2MercName.setText(FullGame.data.findTeamByName("Mercedes").driver2.fname + " " + FullGame.data.findTeamByName("Mercedes").driver2.lname);
        lblD2MercName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2MercName.setOpaque(true);

        lblBalMercValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalMercValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalMercValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalMercValue.setText("$" + FullGame.data.findTeamByName("Mercedes").balance);
        lblBalMercValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalMercValue.setOpaque(true);

        lblBalMerc.setBackground(new java.awt.Color(113, 132, 137));
        lblBalMerc.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalMerc.setForeground(new java.awt.Color(255, 255, 255));
        lblBalMerc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalMerc.setText("Starting Balance");
        lblBalMerc.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalMerc.setOpaque(true);

        javax.swing.GroupLayout pnlMercedesLayout = new javax.swing.GroupLayout(pnlMercedes);
        pnlMercedes.setLayout(pnlMercedesLayout);
        pnlMercedesLayout.setHorizontalGroup(
            pnlMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercedesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMercedesLayout.createSequentialGroup()
                        .addComponent(lblD1Merc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1MercName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMercedesLayout.createSequentialGroup()
                        .addComponent(lblD2Merc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2MercName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMercedesLayout.createSequentialGroup()
                        .addComponent(lblBalMerc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalMercValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlMercedesLayout.setVerticalGroup(
            pnlMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercedesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Merc)
                    .addComponent(lblD1MercName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Merc)
                    .addComponent(lblD2MercName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalMerc)
                    .addComponent(lblBalMercValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Mercedes", pnlMercedes);

        pnlFerrari.setBackground(new java.awt.Color(88, 103, 108));
        pnlFerrari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 0, 0), 3));
        pnlFerrari.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Ferr.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Ferr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Ferr.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Ferr.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Ferr.setText("Driver 1");
        lblD1Ferr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1Ferr.setOpaque(true);

        lblD1FerrName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1FerrName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1FerrName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1FerrName.setText(FullGame.data.findTeamByName("Ferrari").driver1.fname + " " + FullGame.data.findTeamByName("Ferrari").driver1.lname);
        lblD1FerrName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1FerrName.setOpaque(true);

        lblD2Ferr.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Ferr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Ferr.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Ferr.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Ferr.setText("Driver 2");
        lblD2Ferr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2Ferr.setOpaque(true);

        lblD2FerrName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2FerrName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2FerrName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2FerrName.setText(FullGame.data.findTeamByName("Ferrari").driver2.fname + " " + FullGame.data.findTeamByName("Ferrari").driver2.lname);
        lblD2FerrName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2FerrName.setOpaque(true);

        lblBalFerrValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalFerrValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalFerrValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalFerrValue.setText("$" + FullGame.data.findTeamByName("Ferrari").balance);
        lblBalFerrValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalFerrValue.setOpaque(true);

        lblBalFerr.setBackground(new java.awt.Color(113, 132, 137));
        lblBalFerr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalFerr.setForeground(new java.awt.Color(255, 255, 255));
        lblBalFerr.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalFerr.setText("Starting Balance");
        lblBalFerr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalFerr.setOpaque(true);

        javax.swing.GroupLayout pnlFerrariLayout = new javax.swing.GroupLayout(pnlFerrari);
        pnlFerrari.setLayout(pnlFerrariLayout);
        pnlFerrariLayout.setHorizontalGroup(
            pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerrariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(lblD1Ferr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1FerrName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(lblD2Ferr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2FerrName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFerrariLayout.createSequentialGroup()
                        .addComponent(lblBalFerr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalFerrValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlFerrariLayout.setVerticalGroup(
            pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerrariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Ferr)
                    .addComponent(lblD1FerrName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Ferr)
                    .addComponent(lblD2FerrName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalFerr)
                    .addComponent(lblBalFerrValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Ferrari", pnlFerrari);

        pnlRedBull.setBackground(new java.awt.Color(88, 103, 108));
        pnlRedBull.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 65, 255), 3));
        pnlRedBull.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1RBR.setBackground(new java.awt.Color(113, 132, 137));
        lblD1RBR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1RBR.setForeground(new java.awt.Color(255, 255, 255));
        lblD1RBR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1RBR.setText("Driver 1");
        lblD1RBR.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1RBR.setOpaque(true);

        lblD1RBRName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1RBRName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1RBRName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1RBRName.setText(FullGame.data.findTeamByName("Red Bull").driver1.fname + " " + FullGame.data.findTeamByName("Red Bull").driver1.lname);
        lblD1RBRName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1RBRName.setOpaque(true);

        lblD2RBR.setBackground(new java.awt.Color(113, 132, 137));
        lblD2RBR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2RBR.setForeground(new java.awt.Color(255, 255, 255));
        lblD2RBR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2RBR.setText("Driver 2");
        lblD2RBR.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2RBR.setOpaque(true);

        lblD2RBRName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2RBRName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2RBRName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2RBRName.setText(FullGame.data.findTeamByName("Red Bull").driver2.fname + " " + FullGame.data.findTeamByName("Red Bull").driver2.lname);
        lblD2RBRName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2RBRName.setOpaque(true);

        lblBalRBRValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalRBRValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalRBRValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalRBRValue.setText("$" + FullGame.data.findTeamByName("Red Bull").balance);
        lblBalRBRValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalRBRValue.setOpaque(true);

        lblBalRBR.setBackground(new java.awt.Color(113, 132, 137));
        lblBalRBR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalRBR.setForeground(new java.awt.Color(255, 255, 255));
        lblBalRBR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalRBR.setText("Starting Balance");
        lblBalRBR.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalRBR.setOpaque(true);

        javax.swing.GroupLayout pnlRedBullLayout = new javax.swing.GroupLayout(pnlRedBull);
        pnlRedBull.setLayout(pnlRedBullLayout);
        pnlRedBullLayout.setHorizontalGroup(
            pnlRedBullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedBullLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRedBullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRedBullLayout.createSequentialGroup()
                        .addComponent(lblD1RBR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1RBRName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRedBullLayout.createSequentialGroup()
                        .addComponent(lblD2RBR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2RBRName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRedBullLayout.createSequentialGroup()
                        .addComponent(lblBalRBR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalRBRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlRedBullLayout.setVerticalGroup(
            pnlRedBullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedBullLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRedBullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1RBR)
                    .addComponent(lblD1RBRName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRedBullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2RBR)
                    .addComponent(lblD2RBRName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRedBullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalRBR)
                    .addComponent(lblBalRBRValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Red Bull", pnlRedBull);

        pnlMcLaren.setBackground(new java.awt.Color(88, 103, 108));
        pnlMcLaren.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 135, 0), 3));
        pnlMcLaren.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Mcl.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Mcl.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Mcl.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Mcl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Mcl.setText("Driver 1");
        lblD1Mcl.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1Mcl.setOpaque(true);

        lblD1MclName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1MclName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1MclName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1MclName.setText(FullGame.data.findTeamByName("McLaren").driver1.fname + " " + FullGame.data.findTeamByName("McLaren").driver1.lname);
        lblD1MclName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1MclName.setOpaque(true);

        lblD2Mcl.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Mcl.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Mcl.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Mcl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Mcl.setText("Driver 2");
        lblD2Mcl.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2Mcl.setOpaque(true);

        lblD2MclName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2MclName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2MclName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2MclName.setText(FullGame.data.findTeamByName("McLaren").driver2.fname + " " + FullGame.data.findTeamByName("McLaren").driver2.lname);
        lblD2MclName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2MclName.setOpaque(true);

        lblBalMclValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalMclValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalMclValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalMclValue.setText("$" + FullGame.data.findTeamByName("McLaren").balance);
        lblBalMclValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalMclValue.setOpaque(true);

        lblBalMcl.setBackground(new java.awt.Color(113, 132, 137));
        lblBalMcl.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalMcl.setForeground(new java.awt.Color(255, 255, 255));
        lblBalMcl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalMcl.setText("Starting Balance");
        lblBalMcl.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalMcl.setOpaque(true);

        javax.swing.GroupLayout pnlMcLarenLayout = new javax.swing.GroupLayout(pnlMcLaren);
        pnlMcLaren.setLayout(pnlMcLarenLayout);
        pnlMcLarenLayout.setHorizontalGroup(
            pnlMcLarenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMcLarenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMcLarenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMcLarenLayout.createSequentialGroup()
                        .addComponent(lblD1Mcl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1MclName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMcLarenLayout.createSequentialGroup()
                        .addComponent(lblD2Mcl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2MclName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMcLarenLayout.createSequentialGroup()
                        .addComponent(lblBalMcl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalMclValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlMcLarenLayout.setVerticalGroup(
            pnlMcLarenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMcLarenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMcLarenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Mcl)
                    .addComponent(lblD1MclName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMcLarenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Mcl)
                    .addComponent(lblD2MclName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMcLarenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalMcl)
                    .addComponent(lblBalMclValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("McLaren", pnlMcLaren);

        pnlRenault.setBackground(new java.awt.Color(88, 103, 108));
        pnlRenault.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 245, 0), 3));
        pnlRenault.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Ren.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Ren.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Ren.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Ren.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Ren.setText("Driver 1");
        lblD1Ren.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1Ren.setOpaque(true);

        lblD1RenName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1RenName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1RenName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1RenName.setText(FullGame.data.findTeamByName("Renault").driver1.fname + " " + FullGame.data.findTeamByName("Renault").driver1.lname);
        lblD1RenName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1RenName.setOpaque(true);

        lblD2Ren.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Ren.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Ren.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Ren.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Ren.setText("Driver 2");
        lblD2Ren.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2Ren.setOpaque(true);

        lblD2RenName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2RenName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2RenName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2RenName.setText(FullGame.data.findTeamByName("Renault").driver2.fname + " " + FullGame.data.findTeamByName("Renault").driver2.lname);
        lblD2RenName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2RenName.setOpaque(true);

        lblBalRenValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalRenValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalRenValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalRenValue.setText("$" + FullGame.data.findTeamByName("Renault").balance);
        lblBalRenValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalRenValue.setOpaque(true);

        lblBalRen.setBackground(new java.awt.Color(113, 132, 137));
        lblBalRen.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalRen.setForeground(new java.awt.Color(255, 255, 255));
        lblBalRen.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalRen.setText("Starting Balance");
        lblBalRen.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalRen.setOpaque(true);

        javax.swing.GroupLayout pnlRenaultLayout = new javax.swing.GroupLayout(pnlRenault);
        pnlRenault.setLayout(pnlRenaultLayout);
        pnlRenaultLayout.setHorizontalGroup(
            pnlRenaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRenaultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRenaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRenaultLayout.createSequentialGroup()
                        .addComponent(lblD1Ren, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1RenName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRenaultLayout.createSequentialGroup()
                        .addComponent(lblD2Ren, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2RenName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRenaultLayout.createSequentialGroup()
                        .addComponent(lblBalRen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalRenValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlRenaultLayout.setVerticalGroup(
            pnlRenaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRenaultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRenaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Ren)
                    .addComponent(lblD1RenName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRenaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Ren)
                    .addComponent(lblD2RenName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRenaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalRen)
                    .addComponent(lblBalRenValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Renault", pnlRenault);

        pnlToroRosso.setBackground(new java.awt.Color(88, 103, 108));
        pnlToroRosso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 155, 255), 3));
        pnlToroRosso.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1STR.setBackground(new java.awt.Color(113, 132, 137));
        lblD1STR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1STR.setForeground(new java.awt.Color(255, 255, 255));
        lblD1STR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1STR.setText("Driver 1");
        lblD1STR.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1STR.setOpaque(true);

        lblD1STRName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1STRName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1STRName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1STRName.setText(FullGame.data.findTeamByName("Toro Rosso").driver1.fname + " " + FullGame.data.findTeamByName("Toro Rosso").driver1.lname);
        lblD1STRName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1STRName.setOpaque(true);

        lblD2STR.setBackground(new java.awt.Color(113, 132, 137));
        lblD2STR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2STR.setForeground(new java.awt.Color(255, 255, 255));
        lblD2STR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2STR.setText("Driver 2");
        lblD2STR.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2STR.setOpaque(true);

        lblD2STRName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2STRName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2STRName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2STRName.setText(FullGame.data.findTeamByName("Toro Rosso").driver2.fname + " " + FullGame.data.findTeamByName("Toro Rosso").driver2.lname);
        lblD2STRName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2STRName.setOpaque(true);

        lblBalSTRValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalSTRValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalSTRValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalSTRValue.setText("$" + FullGame.data.findTeamByName("Toro Rosso").balance);
        lblBalSTRValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalSTRValue.setOpaque(true);

        lblBalSTR.setBackground(new java.awt.Color(113, 132, 137));
        lblBalSTR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalSTR.setForeground(new java.awt.Color(255, 255, 255));
        lblBalSTR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalSTR.setText("Starting Balance");
        lblBalSTR.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalSTR.setOpaque(true);

        javax.swing.GroupLayout pnlToroRossoLayout = new javax.swing.GroupLayout(pnlToroRosso);
        pnlToroRosso.setLayout(pnlToroRossoLayout);
        pnlToroRossoLayout.setHorizontalGroup(
            pnlToroRossoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToroRossoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToroRossoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlToroRossoLayout.createSequentialGroup()
                        .addComponent(lblD1STR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1STRName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlToroRossoLayout.createSequentialGroup()
                        .addComponent(lblD2STR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2STRName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlToroRossoLayout.createSequentialGroup()
                        .addComponent(lblBalSTR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalSTRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlToroRossoLayout.setVerticalGroup(
            pnlToroRossoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToroRossoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToroRossoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1STR)
                    .addComponent(lblD1STRName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlToroRossoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2STR)
                    .addComponent(lblD2STRName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlToroRossoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalSTR)
                    .addComponent(lblBalSTRValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Toro Rosso", pnlToroRosso);

        pnlRacingPoint.setBackground(new java.awt.Color(88, 103, 108));
        pnlRacingPoint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 150, 200), 3));
        pnlRacingPoint.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1RPt.setBackground(new java.awt.Color(113, 132, 137));
        lblD1RPt.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1RPt.setForeground(new java.awt.Color(255, 255, 255));
        lblD1RPt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1RPt.setText("Driver 1");
        lblD1RPt.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1RPt.setOpaque(true);

        lblD1RPtName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1RPtName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1RPtName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1RPtName.setText(FullGame.data.findTeamByName("Racing Point").driver1.fname + " " + FullGame.data.findTeamByName("Racing Point").driver1.lname);
        lblD1RPtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1RPtName.setOpaque(true);

        lblD2RPt.setBackground(new java.awt.Color(113, 132, 137));
        lblD2RPt.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2RPt.setForeground(new java.awt.Color(255, 255, 255));
        lblD2RPt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2RPt.setText("Driver 2");
        lblD2RPt.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2RPt.setOpaque(true);

        lblD2RPtName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2RPtName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2RPtName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2RPtName.setText(FullGame.data.findTeamByName("Racing Point").driver2.fname + " " + FullGame.data.findTeamByName("Racing Point").driver2.lname);
        lblD2RPtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2RPtName.setOpaque(true);

        lblBalRPtValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalRPtValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalRPtValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalRPtValue.setText("$" + FullGame.data.findTeamByName("Racing Point").balance);
        lblBalRPtValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalRPtValue.setOpaque(true);

        lblBalRPt.setBackground(new java.awt.Color(113, 132, 137));
        lblBalRPt.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalRPt.setForeground(new java.awt.Color(255, 255, 255));
        lblBalRPt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalRPt.setText("Starting Balance");
        lblBalRPt.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalRPt.setOpaque(true);

        javax.swing.GroupLayout pnlRacingPointLayout = new javax.swing.GroupLayout(pnlRacingPoint);
        pnlRacingPoint.setLayout(pnlRacingPointLayout);
        pnlRacingPointLayout.setHorizontalGroup(
            pnlRacingPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRacingPointLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRacingPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRacingPointLayout.createSequentialGroup()
                        .addComponent(lblD1RPt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1RPtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRacingPointLayout.createSequentialGroup()
                        .addComponent(lblD2RPt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2RPtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRacingPointLayout.createSequentialGroup()
                        .addComponent(lblBalRPt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalRPtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlRacingPointLayout.setVerticalGroup(
            pnlRacingPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRacingPointLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRacingPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1RPt)
                    .addComponent(lblD1RPtName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRacingPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2RPt)
                    .addComponent(lblD2RPtName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRacingPointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalRPt)
                    .addComponent(lblBalRPtValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Racing Point", pnlRacingPoint);

        pnlAlfaRomeo.setBackground(new java.awt.Color(88, 103, 108));
        pnlAlfaRomeo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 0, 0), 3));
        pnlAlfaRomeo.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Alfa.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Alfa.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Alfa.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Alfa.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Alfa.setText("Driver 1");
        lblD1Alfa.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        lblD1AlfaName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1AlfaName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1AlfaName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1AlfaName.setText(FullGame.data.findTeamByName("Alfa Romeo").driver1.fname + " " + FullGame.data.findTeamByName("Alfa Romeo").driver1.lname);
        lblD1AlfaName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        lblD2Alfa.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Alfa.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Alfa.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Alfa.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Alfa.setText("Driver 2");
        lblD2Alfa.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        lblD2AlfaName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2AlfaName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2AlfaName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2AlfaName.setText(FullGame.data.findTeamByName("Alfa Romeo").driver2.fname + " " + FullGame.data.findTeamByName("Alfa Romeo").driver2.lname);
        lblD2AlfaName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        lblBalAlfaValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalAlfaValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalAlfaValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalAlfaValue.setText("$" + FullGame.data.findTeamByName("Alfa Romeo").balance);
        lblBalAlfaValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        lblBalAlfa.setBackground(new java.awt.Color(113, 132, 137));
        lblBalAlfa.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalAlfa.setForeground(new java.awt.Color(255, 255, 255));
        lblBalAlfa.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalAlfa.setText("Starting Balance");
        lblBalAlfa.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        javax.swing.GroupLayout pnlAlfaRomeoLayout = new javax.swing.GroupLayout(pnlAlfaRomeo);
        pnlAlfaRomeo.setLayout(pnlAlfaRomeoLayout);
        pnlAlfaRomeoLayout.setHorizontalGroup(
            pnlAlfaRomeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlfaRomeoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlfaRomeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlfaRomeoLayout.createSequentialGroup()
                        .addComponent(lblD1Alfa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1AlfaName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAlfaRomeoLayout.createSequentialGroup()
                        .addComponent(lblD2Alfa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2AlfaName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAlfaRomeoLayout.createSequentialGroup()
                        .addComponent(lblBalAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalAlfaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlAlfaRomeoLayout.setVerticalGroup(
            pnlAlfaRomeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlfaRomeoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlfaRomeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Alfa)
                    .addComponent(lblD1AlfaName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlfaRomeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Alfa)
                    .addComponent(lblD2AlfaName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlfaRomeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalAlfa)
                    .addComponent(lblBalAlfaValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Alfa Romeo", pnlAlfaRomeo);

        pnlHaas.setBackground(new java.awt.Color(88, 103, 108));
        pnlHaas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 215, 135), 3));
        pnlHaas.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Haas.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Haas.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Haas.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Haas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Haas.setText("Driver 1");
        lblD1Haas.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1Haas.setOpaque(true);

        lblD1HaasName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1HaasName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1HaasName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1HaasName.setText(FullGame.data.findTeamByName("Haas").driver1.fname + " " + FullGame.data.findTeamByName("Haas").driver1.lname);
        lblD1HaasName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1HaasName.setOpaque(true);

        lblD2Haas.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Haas.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Haas.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Haas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Haas.setText("Driver 2");
        lblD2Haas.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2Haas.setOpaque(true);

        lblD2HaasName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2HaasName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2HaasName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2HaasName.setText(FullGame.data.findTeamByName("Haas").driver2.fname + " " + FullGame.data.findTeamByName("Haas").driver2.lname);
        lblD2HaasName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2HaasName.setOpaque(true);

        lblBalHaasValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalHaasValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalHaasValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalHaasValue.setText("$" + FullGame.data.findTeamByName("Haas").balance);
        lblBalHaasValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalHaasValue.setOpaque(true);

        lblBalHaas.setBackground(new java.awt.Color(113, 132, 137));
        lblBalHaas.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalHaas.setForeground(new java.awt.Color(255, 255, 255));
        lblBalHaas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalHaas.setText("Starting Balance");
        lblBalHaas.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalHaas.setOpaque(true);

        javax.swing.GroupLayout pnlHaasLayout = new javax.swing.GroupLayout(pnlHaas);
        pnlHaas.setLayout(pnlHaasLayout);
        pnlHaasLayout.setHorizontalGroup(
            pnlHaasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHaasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHaasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHaasLayout.createSequentialGroup()
                        .addComponent(lblD1Haas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1HaasName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHaasLayout.createSequentialGroup()
                        .addComponent(lblD2Haas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2HaasName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHaasLayout.createSequentialGroup()
                        .addComponent(lblBalHaas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalHaasValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlHaasLayout.setVerticalGroup(
            pnlHaasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHaasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHaasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Haas)
                    .addComponent(lblD1HaasName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHaasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Haas)
                    .addComponent(lblD2HaasName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHaasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalHaas)
                    .addComponent(lblBalHaasValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Haas", pnlHaas);

        pnlWilliams.setBackground(new java.awt.Color(88, 103, 108));
        pnlWilliams.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        pnlWilliams.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N

        lblD1Will.setBackground(new java.awt.Color(113, 132, 137));
        lblD1Will.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1Will.setForeground(new java.awt.Color(255, 255, 255));
        lblD1Will.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD1Will.setText("Driver 1");
        lblD1Will.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1Will.setOpaque(true);

        lblD1WillName.setBackground(new java.awt.Color(113, 132, 137));
        lblD1WillName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD1WillName.setForeground(new java.awt.Color(255, 255, 255));
        lblD1WillName.setText(FullGame.data.findTeamByName("Williams").driver1.fname + " " + FullGame.data.findTeamByName("Williams").driver1.lname);
        lblD1WillName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD1WillName.setOpaque(true);

        lblD2Will.setBackground(new java.awt.Color(113, 132, 137));
        lblD2Will.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2Will.setForeground(new java.awt.Color(255, 255, 255));
        lblD2Will.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblD2Will.setText("Driver 2");
        lblD2Will.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2Will.setOpaque(true);

        lblD2WillName.setBackground(new java.awt.Color(113, 132, 137));
        lblD2WillName.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblD2WillName.setForeground(new java.awt.Color(255, 255, 255));
        lblD2WillName.setText(FullGame.data.findTeamByName("Williams").driver2.fname + " " + FullGame.data.findTeamByName("Williams").driver2.lname);
        lblD2WillName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblD2WillName.setOpaque(true);

        lblBalWillValue.setBackground(new java.awt.Color(113, 132, 137));
        lblBalWillValue.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalWillValue.setForeground(new java.awt.Color(255, 255, 255));
        lblBalWillValue.setText("$" + FullGame.data.findTeamByName("Williams").balance);
        lblBalWillValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalWillValue.setOpaque(true);

        lblBalWill.setBackground(new java.awt.Color(113, 132, 137));
        lblBalWill.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblBalWill.setForeground(new java.awt.Color(255, 255, 255));
        lblBalWill.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalWill.setText("Starting Balance");
        lblBalWill.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblBalWill.setOpaque(true);

        javax.swing.GroupLayout pnlWilliamsLayout = new javax.swing.GroupLayout(pnlWilliams);
        pnlWilliams.setLayout(pnlWilliamsLayout);
        pnlWilliamsLayout.setHorizontalGroup(
            pnlWilliamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWilliamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWilliamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWilliamsLayout.createSequentialGroup()
                        .addComponent(lblD1Will, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD1WillName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWilliamsLayout.createSequentialGroup()
                        .addComponent(lblD2Will, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2WillName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWilliamsLayout.createSequentialGroup()
                        .addComponent(lblBalWill, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBalWillValue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        pnlWilliamsLayout.setVerticalGroup(
            pnlWilliamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWilliamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWilliamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1Will)
                    .addComponent(lblD1WillName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlWilliamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD2Will)
                    .addComponent(lblD2WillName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlWilliamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalWill)
                    .addComponent(lblBalWillValue))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        teamsTabs.addTab("Williams", pnlWilliams);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamsTabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamsTabs)
                .addContainerGap())
        );

        teamsTabs.getAccessibleContext().setAccessibleName("Teams");
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel lblBalAlfa;
    protected javax.swing.JLabel lblBalAlfaValue;
    protected javax.swing.JLabel lblBalFerr;
    protected javax.swing.JLabel lblBalFerrValue;
    protected javax.swing.JLabel lblBalHaas;
    protected javax.swing.JLabel lblBalHaasValue;
    protected javax.swing.JLabel lblBalMcl;
    protected javax.swing.JLabel lblBalMclValue;
    protected javax.swing.JLabel lblBalMerc;
    protected javax.swing.JLabel lblBalMercValue;
    protected javax.swing.JLabel lblBalRBR;
    protected javax.swing.JLabel lblBalRBRValue;
    protected javax.swing.JLabel lblBalRPt;
    protected javax.swing.JLabel lblBalRPtValue;
    protected javax.swing.JLabel lblBalRen;
    protected javax.swing.JLabel lblBalRenValue;
    protected javax.swing.JLabel lblBalSTR;
    protected javax.swing.JLabel lblBalSTRValue;
    protected javax.swing.JLabel lblBalWill;
    protected javax.swing.JLabel lblBalWillValue;
    protected javax.swing.JLabel lblD1Alfa;
    protected javax.swing.JLabel lblD1AlfaName;
    protected javax.swing.JLabel lblD1Ferr;
    protected javax.swing.JLabel lblD1FerrName;
    protected javax.swing.JLabel lblD1Haas;
    protected javax.swing.JLabel lblD1HaasName;
    protected javax.swing.JLabel lblD1Mcl;
    protected javax.swing.JLabel lblD1MclName;
    protected javax.swing.JLabel lblD1Merc;
    protected javax.swing.JLabel lblD1MercName;
    protected javax.swing.JLabel lblD1RBR;
    protected javax.swing.JLabel lblD1RBRName;
    protected javax.swing.JLabel lblD1RPt;
    protected javax.swing.JLabel lblD1RPtName;
    protected javax.swing.JLabel lblD1Ren;
    protected javax.swing.JLabel lblD1RenName;
    protected javax.swing.JLabel lblD1STR;
    protected javax.swing.JLabel lblD1STRName;
    protected javax.swing.JLabel lblD1Will;
    protected javax.swing.JLabel lblD1WillName;
    protected javax.swing.JLabel lblD2Alfa;
    protected javax.swing.JLabel lblD2AlfaName;
    protected javax.swing.JLabel lblD2Ferr;
    protected javax.swing.JLabel lblD2FerrName;
    protected javax.swing.JLabel lblD2Haas;
    protected javax.swing.JLabel lblD2HaasName;
    protected javax.swing.JLabel lblD2Mcl;
    protected javax.swing.JLabel lblD2MclName;
    protected javax.swing.JLabel lblD2Merc;
    protected javax.swing.JLabel lblD2MercName;
    protected javax.swing.JLabel lblD2RBR;
    protected javax.swing.JLabel lblD2RBRName;
    protected javax.swing.JLabel lblD2RPt;
    protected javax.swing.JLabel lblD2RPtName;
    protected javax.swing.JLabel lblD2Ren;
    protected javax.swing.JLabel lblD2RenName;
    protected javax.swing.JLabel lblD2STR;
    protected javax.swing.JLabel lblD2STRName;
    protected javax.swing.JLabel lblD2Will;
    protected javax.swing.JLabel lblD2WillName;
    protected javax.swing.JPanel pnlAlfaRomeo;
    protected javax.swing.JPanel pnlFerrari;
    protected javax.swing.JPanel pnlHaas;
    protected javax.swing.JPanel pnlMcLaren;
    protected javax.swing.JPanel pnlMercedes;
    protected javax.swing.JPanel pnlRacingPoint;
    protected javax.swing.JPanel pnlRedBull;
    protected javax.swing.JPanel pnlRenault;
    protected javax.swing.JPanel pnlToroRosso;
    protected javax.swing.JPanel pnlWilliams;
    protected javax.swing.JTabbedPane teamsTabs;
    // End of variables declaration//GEN-END:variables
}
