/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui.engineering;

/**
 *
 * @author Josh Brookes
 */
public class EnAll extends javax.swing.JPanel {

    /**
     * Creates new form EnAll
     */
    public EnAll() {
        initComponents();
        initOther();
    }
    
    private void initOther() {

        enGarage1 = new grandprixworld.gui.engineering.EnGarage();
        enTesting1 = new grandprixworld.gui.engineering.EnTesting();
        enDesign1 = new grandprixworld.gui.engineering.EnDesign();
        enConstruction1 = new grandprixworld.gui.engineering.EnConstruction();
        enContracts1 = new grandprixworld.gui.engineering.EnContracts();
        enFactory1 = new grandprixworld.gui.engineering.EnFactory();

        setBackground(new java.awt.Color(64, 64, 64));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setPreferredSize(new java.awt.Dimension(1100, 550));
        setLayout(new java.awt.CardLayout());
        add(enGarage1, "Garage");
        add(enTesting1, "Testing");
        add(enDesign1, "Design");
        add(enConstruction1, "Construction");
        add(enContracts1, "Contracts");
        add(enFactory1, "Factory");
    }
    
    public void updateScreenData() {
        enGarage1.updateScreenData();
        enTesting1.updateScreenData();
        enDesign1.updateScreenData();
        enConstruction1.updateScreenData();
        enContracts1.updateScreenData();
        //enFactory1.updateScreenData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(64, 64, 64));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setPreferredSize(new java.awt.Dimension(1100, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public grandprixworld.gui.engineering.EnConstruction enConstruction1;
    private grandprixworld.gui.engineering.EnContracts enContracts1;
    public grandprixworld.gui.engineering.EnDesign enDesign1;
    private grandprixworld.gui.engineering.EnFactory enFactory1;
    public grandprixworld.gui.engineering.EnGarage enGarage1;
    public grandprixworld.gui.engineering.EnTesting enTesting1;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
