/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui.engineering;

import grandprixworld.gui.FullGame;

/**
 *
 * @author Josh Brookes
 */
public class EnFactory extends javax.swing.JPanel {

    /**
     * Creates new form EnFactory
     */
    public EnFactory() {
        initComponents();
        updateScreenData();
    }
    
    public void updateScreenData() {
        imgFactorySize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5ability" + FullGame.data.findPlayerTeam().factory.size + ".png")));
        lblStaffLimit.setText(Integer.toString(FullGame.data.findPlayerTeam().factory.maxStaff()));
        lblDepartmentLimit.setText(Integer.toString(FullGame.data.findPlayerTeam().factory.maxDepartment()));
        lblFacilityLimit.setText(Integer.toString(FullGame.data.findPlayerTeam().factory.maxFacility()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        imgFactorySize = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        lblOverhead = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        lblStaffLimit = new javax.swing.JLabel();
        lblDepartmentLimit = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        lblFacilityLimit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel335 = new javax.swing.JLabel();
        jLabel336 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel337 = new javax.swing.JLabel();
        jLabel338 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel339 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel340 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel341 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel342 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel343 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel344 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel345 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel346 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(88, 103, 108));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jPanel3.setOpaque(false);

        jLabel119.setBackground(new java.awt.Color(113, 132, 137));
        jLabel119.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(255, 255, 255));
        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel119.setText("Factory Data");
        jLabel119.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel119.setOpaque(true);

        jLabel120.setBackground(new java.awt.Color(113, 132, 137));
        jLabel120.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel120.setText("Size");
        jLabel120.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel120.setOpaque(true);

        imgFactorySize.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        imgFactorySize.setForeground(new java.awt.Color(255, 255, 255));
        imgFactorySize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5ability5.png"))); // NOI18N

        jLabel121.setBackground(new java.awt.Color(113, 132, 137));
        jLabel121.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 255, 255));
        jLabel121.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel121.setText("Overheads");
        jLabel121.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel121.setOpaque(true);

        lblOverhead.setBackground(new java.awt.Color(113, 132, 137));
        lblOverhead.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblOverhead.setForeground(new java.awt.Color(255, 255, 255));
        lblOverhead.setText("$1,000,000");
        lblOverhead.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblOverhead.setOpaque(true);

        jLabel122.setBackground(new java.awt.Color(113, 132, 137));
        jLabel122.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(255, 255, 255));
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel122.setText("Staff Limit");
        jLabel122.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel122.setOpaque(true);

        lblStaffLimit.setBackground(new java.awt.Color(113, 132, 137));
        lblStaffLimit.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblStaffLimit.setForeground(new java.awt.Color(255, 255, 255));
        lblStaffLimit.setText(" ");
        lblStaffLimit.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblStaffLimit.setOpaque(true);

        lblDepartmentLimit.setBackground(new java.awt.Color(113, 132, 137));
        lblDepartmentLimit.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblDepartmentLimit.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartmentLimit.setText(" ");
        lblDepartmentLimit.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblDepartmentLimit.setOpaque(true);

        jLabel123.setBackground(new java.awt.Color(113, 132, 137));
        jLabel123.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(255, 255, 255));
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel123.setText("Department Limit");
        jLabel123.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel123.setOpaque(true);

        jLabel124.setBackground(new java.awt.Color(113, 132, 137));
        jLabel124.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(255, 255, 255));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel124.setText("Facility Limit");
        jLabel124.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel124.setOpaque(true);

        lblFacilityLimit.setBackground(new java.awt.Color(113, 132, 137));
        lblFacilityLimit.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblFacilityLimit.setForeground(new java.awt.Color(255, 255, 255));
        lblFacilityLimit.setText(" ");
        lblFacilityLimit.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblFacilityLimit.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel121, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel120, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel122, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabel124, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgFactorySize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOverhead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStaffLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDepartmentLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFacilityLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel119)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel120, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgFactorySize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOverhead)
                    .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel122)
                    .addComponent(lblStaffLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel123)
                    .addComponent(lblDepartmentLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel124)
                    .addComponent(lblFacilityLimit))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        add(jPanel1);

        jPanel2.setOpaque(false);

        jLabel125.setBackground(new java.awt.Color(113, 132, 137));
        jLabel125.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(255, 255, 255));
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("Facilities");
        jLabel125.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel125.setOpaque(true);

        jLabel126.setBackground(new java.awt.Color(113, 132, 137));
        jLabel126.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(255, 255, 255));
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText("Facility");
        jLabel126.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel126.setOpaque(true);

        jLabel127.setBackground(new java.awt.Color(113, 132, 137));
        jLabel127.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("Improve");
        jLabel127.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel127.setOpaque(true);

        jLabel128.setBackground(new java.awt.Color(113, 132, 137));
        jLabel128.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 255));
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText("Ready");
        jLabel128.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel128.setOpaque(true);

        jLabel129.setBackground(new java.awt.Color(113, 132, 137));
        jLabel129.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(255, 255, 255));
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("Total Cost");
        jLabel129.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel129.setOpaque(true);

        jLabel130.setBackground(new java.awt.Color(113, 132, 137));
        jLabel130.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(255, 255, 255));
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel130.setText("Cost Per Month");
        jLabel130.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel130.setOpaque(true);

        jLabel131.setBackground(new java.awt.Color(113, 132, 137));
        jLabel131.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jLabel131.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel131.setText("Build");
        jLabel131.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel131.setOpaque(true);

        jLabel132.setBackground(new java.awt.Color(113, 132, 137));
        jLabel132.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(255, 255, 255));
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setText("Sell");
        jLabel132.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel132.setOpaque(true);

        jLabel137.setBackground(new java.awt.Color(113, 132, 137));
        jLabel137.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(255, 255, 255));
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel137.setText("Factory");
        jLabel137.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel137.setOpaque(true);

        jLabel138.setBackground(new java.awt.Color(113, 132, 137));
        jLabel138.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 255, 255));
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel138.setText("-");
        jLabel138.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel138.setOpaque(true);

        jLabel139.setBackground(new java.awt.Color(113, 132, 137));
        jLabel139.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel139.setText("$0");
        jLabel139.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel139.setOpaque(true);

        jLabel140.setBackground(new java.awt.Color(113, 132, 137));
        jLabel140.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 255, 255));
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel140.setText("$0");
        jLabel140.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel140.setOpaque(true);

        jLabel335.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel335.setForeground(new java.awt.Color(255, 255, 255));
        jLabel335.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel335.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N

        jLabel336.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel336.setForeground(new java.awt.Color(255, 255, 255));
        jLabel336.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel336.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N

        jLabel199.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel199.setForeground(new java.awt.Color(255, 255, 255));
        jLabel199.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel199.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel199.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel141.setBackground(new java.awt.Color(113, 132, 137));
        jLabel141.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 255, 255));
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel141.setText("CAD");
        jLabel141.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel141.setOpaque(true);

        jLabel337.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel337.setForeground(new java.awt.Color(255, 255, 255));
        jLabel337.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel337.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N

        jLabel338.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel338.setForeground(new java.awt.Color(255, 255, 255));
        jLabel338.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel338.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N

        jLabel142.setBackground(new java.awt.Color(113, 132, 137));
        jLabel142.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(255, 255, 255));
        jLabel142.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel142.setText("-");
        jLabel142.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel142.setOpaque(true);

        jLabel143.setBackground(new java.awt.Color(113, 132, 137));
        jLabel143.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(255, 255, 255));
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setText("$0");
        jLabel143.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel143.setOpaque(true);

        jLabel144.setBackground(new java.awt.Color(113, 132, 137));
        jLabel144.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(255, 255, 255));
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("$0");
        jLabel144.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel144.setOpaque(true);

        jLabel201.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel201.setForeground(new java.awt.Color(255, 255, 255));
        jLabel201.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel201.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel202.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel202.setForeground(new java.awt.Color(255, 255, 255));
        jLabel202.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel202.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel339.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel339.setForeground(new java.awt.Color(255, 255, 255));
        jLabel339.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel339.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N

        jLabel145.setBackground(new java.awt.Color(113, 132, 137));
        jLabel145.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(255, 255, 255));
        jLabel145.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel145.setText("-");
        jLabel145.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel145.setOpaque(true);

        jLabel203.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel203.setForeground(new java.awt.Color(255, 255, 255));
        jLabel203.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel203.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel146.setBackground(new java.awt.Color(113, 132, 137));
        jLabel146.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(255, 255, 255));
        jLabel146.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel146.setText("$0");
        jLabel146.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel146.setOpaque(true);

        jLabel147.setBackground(new java.awt.Color(113, 132, 137));
        jLabel147.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(255, 255, 255));
        jLabel147.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel147.setText("CAM");
        jLabel147.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel147.setOpaque(true);

        jLabel340.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel340.setForeground(new java.awt.Color(255, 255, 255));
        jLabel340.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel340.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N

        jLabel148.setBackground(new java.awt.Color(113, 132, 137));
        jLabel148.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(255, 255, 255));
        jLabel148.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel148.setText("$0");
        jLabel148.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel148.setOpaque(true);

        jLabel204.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel204.setForeground(new java.awt.Color(255, 255, 255));
        jLabel204.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel204.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel204.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel205.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel205.setForeground(new java.awt.Color(255, 255, 255));
        jLabel205.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel205.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel205.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel149.setBackground(new java.awt.Color(113, 132, 137));
        jLabel149.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(255, 255, 255));
        jLabel149.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel149.setText("$0");
        jLabel149.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel149.setOpaque(true);

        jLabel150.setBackground(new java.awt.Color(113, 132, 137));
        jLabel150.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(255, 255, 255));
        jLabel150.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel150.setText("-");
        jLabel150.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel150.setOpaque(true);

        jLabel151.setBackground(new java.awt.Color(113, 132, 137));
        jLabel151.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(255, 255, 255));
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel151.setText("Supercomputer");
        jLabel151.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel151.setOpaque(true);

        jLabel341.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel341.setForeground(new java.awt.Color(255, 255, 255));
        jLabel341.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel341.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N

        jLabel152.setBackground(new java.awt.Color(113, 132, 137));
        jLabel152.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(255, 255, 255));
        jLabel152.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel152.setText("$0");
        jLabel152.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel152.setOpaque(true);

        jLabel342.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel342.setForeground(new java.awt.Color(255, 255, 255));
        jLabel342.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel342.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N

        jLabel206.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel206.setForeground(new java.awt.Color(255, 255, 255));
        jLabel206.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel206.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel206.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel153.setBackground(new java.awt.Color(113, 132, 137));
        jLabel153.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(255, 255, 255));
        jLabel153.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel153.setText("$0");
        jLabel153.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel153.setOpaque(true);

        jLabel154.setBackground(new java.awt.Color(113, 132, 137));
        jLabel154.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(255, 255, 255));
        jLabel154.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel154.setText("$0");
        jLabel154.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel154.setOpaque(true);

        jLabel343.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel343.setForeground(new java.awt.Color(255, 255, 255));
        jLabel343.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel343.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N

        jLabel207.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel207.setForeground(new java.awt.Color(255, 255, 255));
        jLabel207.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel207.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel207.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel155.setBackground(new java.awt.Color(113, 132, 137));
        jLabel155.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(255, 255, 255));
        jLabel155.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel155.setText("Wind Tunnel");
        jLabel155.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel155.setOpaque(true);

        jLabel208.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel208.setForeground(new java.awt.Color(255, 255, 255));
        jLabel208.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel208.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel208.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel156.setBackground(new java.awt.Color(113, 132, 137));
        jLabel156.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jLabel156.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel156.setText("-");
        jLabel156.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel156.setOpaque(true);

        jLabel344.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel344.setForeground(new java.awt.Color(255, 255, 255));
        jLabel344.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel344.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N

        jLabel157.setBackground(new java.awt.Color(113, 132, 137));
        jLabel157.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel157.setText("$0");
        jLabel157.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel157.setOpaque(true);

        jLabel345.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel345.setForeground(new java.awt.Color(255, 255, 255));
        jLabel345.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel345.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N

        jLabel209.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel209.setForeground(new java.awt.Color(255, 255, 255));
        jLabel209.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel209.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel209.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel158.setBackground(new java.awt.Color(113, 132, 137));
        jLabel158.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(255, 255, 255));
        jLabel158.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel158.setText("-");
        jLabel158.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel158.setOpaque(true);

        jLabel210.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel210.setForeground(new java.awt.Color(255, 255, 255));
        jLabel210.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel210.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirm.png"))); // NOI18N
        jLabel210.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));

        jLabel159.setBackground(new java.awt.Color(113, 132, 137));
        jLabel159.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(255, 255, 255));
        jLabel159.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel159.setText("$0");
        jLabel159.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel159.setOpaque(true);

        jLabel160.setBackground(new java.awt.Color(113, 132, 137));
        jLabel160.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(255, 255, 255));
        jLabel160.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel160.setText("Workshop");
        jLabel160.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel160.setOpaque(true);

        jLabel346.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel346.setForeground(new java.awt.Color(255, 255, 255));
        jLabel346.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel346.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel128, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel130, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel131, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel132, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel137, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel335)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel336)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel138, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel140, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel199, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel141, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel337)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel338)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel142, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel201, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel202, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel147, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel340)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel339)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel145, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel148, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel146, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel204, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel203, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel151, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel341)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel342)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel150, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel149, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel152, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel205, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel206, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel155, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel344)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel343)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel156, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel153, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel154, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel207, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel208, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel160, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel346)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel345)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel158, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel157, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel159, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel209, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel210, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel125)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel126)
                    .addComponent(jLabel127)
                    .addComponent(jLabel128)
                    .addComponent(jLabel129)
                    .addComponent(jLabel130)
                    .addComponent(jLabel131)
                    .addComponent(jLabel132))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel137)
                        .addComponent(jLabel138)
                        .addComponent(jLabel139)
                        .addComponent(jLabel140))
                    .addComponent(jLabel335)
                    .addComponent(jLabel336)
                    .addComponent(jLabel199, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel141)
                        .addComponent(jLabel142)
                        .addComponent(jLabel143)
                        .addComponent(jLabel144))
                    .addComponent(jLabel337)
                    .addComponent(jLabel338)
                    .addComponent(jLabel201, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel202, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel147)
                        .addComponent(jLabel145)
                        .addComponent(jLabel148)
                        .addComponent(jLabel146))
                    .addComponent(jLabel340)
                    .addComponent(jLabel339)
                    .addComponent(jLabel204, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel203, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel151)
                        .addComponent(jLabel150)
                        .addComponent(jLabel149)
                        .addComponent(jLabel152))
                    .addComponent(jLabel341)
                    .addComponent(jLabel342)
                    .addComponent(jLabel205, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel206, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel155)
                        .addComponent(jLabel156)
                        .addComponent(jLabel153)
                        .addComponent(jLabel154))
                    .addComponent(jLabel344)
                    .addComponent(jLabel343)
                    .addComponent(jLabel207, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel208, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel160)
                        .addComponent(jLabel158)
                        .addComponent(jLabel157)
                        .addComponent(jLabel159))
                    .addComponent(jLabel346)
                    .addComponent(jLabel345)
                    .addComponent(jLabel209, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel210, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFactorySize;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel335;
    private javax.swing.JLabel jLabel336;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JLabel jLabel340;
    private javax.swing.JLabel jLabel341;
    private javax.swing.JLabel jLabel342;
    private javax.swing.JLabel jLabel343;
    private javax.swing.JLabel jLabel344;
    private javax.swing.JLabel jLabel345;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDepartmentLimit;
    private javax.swing.JLabel lblFacilityLimit;
    private javax.swing.JLabel lblOverhead;
    private javax.swing.JLabel lblStaffLimit;
    // End of variables declaration//GEN-END:variables
}
