/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui.racePrep;

/**
 *
 * @author Josh Brookes
 */
public class rpAll extends javax.swing.JPanel {

    /**
     * Creates new form rpAll
     */
    public rpAll() {
        initComponents();
        initOther();
    }
    
    public void initOther() {
        rpDrivers1 = new grandprixworld.gui.racePrep.rpDrivers();
        rpAssembly1 = new grandprixworld.gui.racePrep.rpAssembly();
        rpChampionship1 = new grandprixworld.gui.racePrep.rpChampionship();
        rpCalendar1 = new grandprixworld.gui.racePrep.rpCalendar();
        rpRegulations1 = new grandprixworld.gui.racePrep.rpRegulations();
        add(rpDrivers1, "Drivers");
        add(rpAssembly1, "Assembly");
        add(rpChampionship1, "Championship");
        add(rpCalendar1, "Calendar");
        add(rpRegulations1, "Regulations");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(64, 64, 64));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    private grandprixworld.gui.racePrep.rpAssembly rpAssembly1;
    public grandprixworld.gui.racePrep.rpCalendar rpCalendar1;
    public grandprixworld.gui.racePrep.rpChampionship rpChampionship1;
    private grandprixworld.gui.racePrep.rpDrivers rpDrivers1;
    private grandprixworld.gui.racePrep.rpRegulations rpRegulations1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
