/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandprixworld.gui.teamOrg;

import java.util.Random;

/**
 *
 * @author Josh Brookes
 */
public class TmHireFire extends javax.swing.JPanel {

    /**
     * Creates new form TmHireFire
     */
    int[] staff = new int[5];
    int[] startStaff = new int[5];
    int[] salaries;
    int[] hire = new int[5];
    int[] redundancy = new int[5];
    int maxStaff;

    public TmHireFire(int dept, int[] hire) {
        initComponents();
        maxStaff = grandprixworld.gui.FullGame.data.getMaxStaff(grandprixworld.gui.FullGame.data.findPlayerTeam().factory.size);
        switch (dept) {
            case 1:
                for (int i = 0; i < 5; i++) {
                    staff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().commStaff[i];
                    startStaff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().commStaff[i];
                }
                salaries = new int[]{75000, 50000, 30000, 20000, 15000};
                break;
            case 2:
                for (int i = 0; i < 5; i++) {
                    staff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().desStaff[i];
                    startStaff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().desStaff[i];
                }
                salaries = new int[]{110000, 70000, 45000, 25000, 15000};
                break;
            case 3:
                for (int i = 0; i < 5; i++) {
                    staff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().techStaff[i];
                    startStaff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().techStaff[i];
                }
                salaries = new int[]{95000, 60000, 40000, 22000, 15000};
                break;
            case 4:
                for (int i = 0; i < 5; i++) {
                    staff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().mechStaff[i];
                    startStaff[i] = grandprixworld.gui.FullGame.data.findPlayerTeam().mechStaff[i];
                }
                salaries = new int[]{55000, 40000, 25000, 20000, 15000};
                break;
        }
        this.hire = hire;
        
        updateScreenData();
    }

    

public void updateScreenData() {
        lblQMax.setText(Integer.toString(maxStaff));
        lblQEx.setText(Integer.toString(staff[0]));
        lblQVG.setText(Integer.toString(staff[1]));
        lblQGd.setText(Integer.toString(staff[2]));
        lblQAv.setText(Integer.toString(staff[3]));
        lblQTr.setText(Integer.toString(staff[4]));
        lblQTotal.setText(Integer.toString(staff[0] + staff[1] + staff[2] + staff[3] + staff[4]));
        lblHEx.setText(Integer.toString(hire[0]));
        lblHVG.setText(Integer.toString(hire[1]));
        lblHGd.setText(Integer.toString(hire[2]));
        lblHAv.setText(Integer.toString(hire[3]));
        lblHTr.setText(Integer.toString(hire[4]));
        lblHTotal.setText(Integer.toString(hire[0] + hire[1] + hire[2] + hire[3] + hire[4]));
        lblREx.setText("$" + Integer.toString(redundancy[0] * salaries[0]));
        lblRVG.setText("$" + Integer.toString(redundancy[1] * salaries[1]));
        lblRGd.setText("$" + Integer.toString(redundancy[2] * salaries[2]));
        lblRAv.setText("$" + Integer.toString(redundancy[3] * salaries[3]));
        lblRTr.setText("$" + Integer.toString(redundancy[4] * salaries[4]));
        lblRTotal.setText("$" + Integer.toString(redundancy[0] * salaries[0] + redundancy[1] * salaries[1] + redundancy[2] * salaries[2] + redundancy[3] * salaries[3] + redundancy[4] * salaries[4]));
        lblSEx.setText("$" + Integer.toString(salaries[0]));
        lblSVG.setText("$" + Integer.toString(salaries[1]));
        lblSGd.setText("$" + Integer.toString(salaries[2]));
        lblSAv.setText("$" + Integer.toString(salaries[3]));
        lblSTr.setText("$" + Integer.toString(salaries[4]));
        lblTEx.setText("$" + Integer.toString(staff[0] * salaries[0]));
        lblTVG.setText("$" + Integer.toString(staff[1] * salaries[1]));
        lblTGd.setText("$" + Integer.toString(staff[2] * salaries[2]));
        lblTAv.setText("$" + Integer.toString(staff[3] * salaries[3]));
        lblTTr.setText("$" + Integer.toString(staff[4] * salaries[4]));
        lblTTotal.setText("$" + Integer.toString(staff[0] * salaries[0] + staff[1] * salaries[1] + staff[2] * salaries[2] + staff[3] * salaries[3] + staff[4] * salaries[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDecEx = new javax.swing.JLabel();
        btnIncEx = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblQEx = new javax.swing.JLabel();
        lblHEx = new javax.swing.JLabel();
        lblREx = new javax.swing.JLabel();
        lblSEx = new javax.swing.JLabel();
        lblTEx = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnDecVG = new javax.swing.JLabel();
        lblRVG = new javax.swing.JLabel();
        lblQVG = new javax.swing.JLabel();
        lblHVG = new javax.swing.JLabel();
        lblSVG = new javax.swing.JLabel();
        lblTVG = new javax.swing.JLabel();
        btnIncVG = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblQGd = new javax.swing.JLabel();
        lblHGd = new javax.swing.JLabel();
        lblTGd = new javax.swing.JLabel();
        lblSGd = new javax.swing.JLabel();
        btnIncGd = new javax.swing.JLabel();
        btnDecGd = new javax.swing.JLabel();
        lblRGd = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnIncAv = new javax.swing.JLabel();
        lblRAv = new javax.swing.JLabel();
        lblSAv = new javax.swing.JLabel();
        btnDecAv = new javax.swing.JLabel();
        lblQAv = new javax.swing.JLabel();
        lblHAv = new javax.swing.JLabel();
        lblTAv = new javax.swing.JLabel();
        lblQTr = new javax.swing.JLabel();
        lblRTr = new javax.swing.JLabel();
        lblHTr = new javax.swing.JLabel();
        btnIncTr = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lblSTr = new javax.swing.JLabel();
        btnDecTr = new javax.swing.JLabel();
        lblTTr = new javax.swing.JLabel();
        lblQTotal = new javax.swing.JLabel();
        lblTTotal = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lblHTotal = new javax.swing.JLabel();
        lblRTotal = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        btnAccept = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lblQMax = new javax.swing.JLabel();

        setBackground(new java.awt.Color(88, 103, 108));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));

        jLabel1.setBackground(new java.awt.Color(113, 132, 137));
        jLabel1.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Quality");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel1.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(113, 132, 137));
        jLabel4.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quantity");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(113, 132, 137));
        jLabel5.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("For Hire");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(113, 132, 137));
        jLabel6.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Redundancy");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(113, 132, 137));
        jLabel7.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Salary");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(113, 132, 137));
        jLabel8.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sub Total");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel8.setOpaque(true);

        btnDecEx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnDecEx.setForeground(new java.awt.Color(255, 255, 255));
        btnDecEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N
        btnDecEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecExMouseClicked(evt);
            }
        });

        btnIncEx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnIncEx.setForeground(new java.awt.Color(255, 255, 255));
        btnIncEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N
        btnIncEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncExMouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(113, 132, 137));
        jLabel11.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Excellent");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel11.setOpaque(true);

        lblQEx.setBackground(new java.awt.Color(113, 132, 137));
        lblQEx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQEx.setForeground(new java.awt.Color(255, 255, 255));
        lblQEx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQEx.setText(" ");
        lblQEx.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQEx.setOpaque(true);

        lblHEx.setBackground(new java.awt.Color(113, 132, 137));
        lblHEx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblHEx.setForeground(new java.awt.Color(255, 255, 255));
        lblHEx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHEx.setText(" ");
        lblHEx.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblHEx.setOpaque(true);

        lblREx.setBackground(new java.awt.Color(113, 132, 137));
        lblREx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblREx.setForeground(new java.awt.Color(255, 255, 255));
        lblREx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblREx.setText(" ");
        lblREx.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblREx.setOpaque(true);

        lblSEx.setBackground(new java.awt.Color(113, 132, 137));
        lblSEx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblSEx.setForeground(new java.awt.Color(255, 255, 255));
        lblSEx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSEx.setText(" ");
        lblSEx.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblSEx.setOpaque(true);

        lblTEx.setBackground(new java.awt.Color(113, 132, 137));
        lblTEx.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblTEx.setForeground(new java.awt.Color(255, 255, 255));
        lblTEx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTEx.setText(" ");
        lblTEx.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblTEx.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(113, 132, 137));
        jLabel17.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Very Good");
        jLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel17.setOpaque(true);

        btnDecVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnDecVG.setForeground(new java.awt.Color(255, 255, 255));
        btnDecVG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N
        btnDecVG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecVGMouseClicked(evt);
            }
        });

        lblRVG.setBackground(new java.awt.Color(113, 132, 137));
        lblRVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblRVG.setForeground(new java.awt.Color(255, 255, 255));
        lblRVG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRVG.setText(" ");
        lblRVG.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblRVG.setOpaque(true);

        lblQVG.setBackground(new java.awt.Color(113, 132, 137));
        lblQVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQVG.setForeground(new java.awt.Color(255, 255, 255));
        lblQVG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQVG.setText(" ");
        lblQVG.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQVG.setOpaque(true);

        lblHVG.setBackground(new java.awt.Color(113, 132, 137));
        lblHVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblHVG.setForeground(new java.awt.Color(255, 255, 255));
        lblHVG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHVG.setText(" ");
        lblHVG.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblHVG.setOpaque(true);

        lblSVG.setBackground(new java.awt.Color(113, 132, 137));
        lblSVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblSVG.setForeground(new java.awt.Color(255, 255, 255));
        lblSVG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSVG.setText(" ");
        lblSVG.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblSVG.setOpaque(true);

        lblTVG.setBackground(new java.awt.Color(113, 132, 137));
        lblTVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblTVG.setForeground(new java.awt.Color(255, 255, 255));
        lblTVG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTVG.setText(" ");
        lblTVG.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblTVG.setOpaque(true);

        btnIncVG.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnIncVG.setForeground(new java.awt.Color(255, 255, 255));
        btnIncVG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N
        btnIncVG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncVGMouseClicked(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(113, 132, 137));
        jLabel25.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("Good");
        jLabel25.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel25.setOpaque(true);

        lblQGd.setBackground(new java.awt.Color(113, 132, 137));
        lblQGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQGd.setForeground(new java.awt.Color(255, 255, 255));
        lblQGd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQGd.setText(" ");
        lblQGd.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQGd.setOpaque(true);

        lblHGd.setBackground(new java.awt.Color(113, 132, 137));
        lblHGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblHGd.setForeground(new java.awt.Color(255, 255, 255));
        lblHGd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHGd.setText(" ");
        lblHGd.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblHGd.setOpaque(true);

        lblTGd.setBackground(new java.awt.Color(113, 132, 137));
        lblTGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblTGd.setForeground(new java.awt.Color(255, 255, 255));
        lblTGd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTGd.setText(" ");
        lblTGd.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblTGd.setOpaque(true);

        lblSGd.setBackground(new java.awt.Color(113, 132, 137));
        lblSGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblSGd.setForeground(new java.awt.Color(255, 255, 255));
        lblSGd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSGd.setText(" ");
        lblSGd.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblSGd.setOpaque(true);

        btnIncGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnIncGd.setForeground(new java.awt.Color(255, 255, 255));
        btnIncGd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N
        btnIncGd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncGdMouseClicked(evt);
            }
        });

        btnDecGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnDecGd.setForeground(new java.awt.Color(255, 255, 255));
        btnDecGd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N
        btnDecGd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecGdMouseClicked(evt);
            }
        });

        lblRGd.setBackground(new java.awt.Color(113, 132, 137));
        lblRGd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblRGd.setForeground(new java.awt.Color(255, 255, 255));
        lblRGd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRGd.setText(" ");
        lblRGd.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblRGd.setOpaque(true);

        jLabel33.setBackground(new java.awt.Color(113, 132, 137));
        jLabel33.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel33.setText("Average");
        jLabel33.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel33.setOpaque(true);

        btnIncAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnIncAv.setForeground(new java.awt.Color(255, 255, 255));
        btnIncAv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N
        btnIncAv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncAvMouseClicked(evt);
            }
        });

        lblRAv.setBackground(new java.awt.Color(113, 132, 137));
        lblRAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblRAv.setForeground(new java.awt.Color(255, 255, 255));
        lblRAv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRAv.setText(" ");
        lblRAv.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblRAv.setOpaque(true);

        lblSAv.setBackground(new java.awt.Color(113, 132, 137));
        lblSAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblSAv.setForeground(new java.awt.Color(255, 255, 255));
        lblSAv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSAv.setText(" ");
        lblSAv.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblSAv.setOpaque(true);

        btnDecAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnDecAv.setForeground(new java.awt.Color(255, 255, 255));
        btnDecAv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N
        btnDecAv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecAvMouseClicked(evt);
            }
        });

        lblQAv.setBackground(new java.awt.Color(113, 132, 137));
        lblQAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQAv.setForeground(new java.awt.Color(255, 255, 255));
        lblQAv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQAv.setText(" ");
        lblQAv.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQAv.setOpaque(true);

        lblHAv.setBackground(new java.awt.Color(113, 132, 137));
        lblHAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblHAv.setForeground(new java.awt.Color(255, 255, 255));
        lblHAv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHAv.setText(" ");
        lblHAv.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblHAv.setOpaque(true);

        lblTAv.setBackground(new java.awt.Color(113, 132, 137));
        lblTAv.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblTAv.setForeground(new java.awt.Color(255, 255, 255));
        lblTAv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTAv.setText(" ");
        lblTAv.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblTAv.setOpaque(true);

        lblQTr.setBackground(new java.awt.Color(113, 132, 137));
        lblQTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQTr.setForeground(new java.awt.Color(255, 255, 255));
        lblQTr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQTr.setText(" ");
        lblQTr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQTr.setOpaque(true);

        lblRTr.setBackground(new java.awt.Color(113, 132, 137));
        lblRTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblRTr.setForeground(new java.awt.Color(255, 255, 255));
        lblRTr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRTr.setText(" ");
        lblRTr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblRTr.setOpaque(true);

        lblHTr.setBackground(new java.awt.Color(113, 132, 137));
        lblHTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblHTr.setForeground(new java.awt.Color(255, 255, 255));
        lblHTr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHTr.setText(" ");
        lblHTr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblHTr.setOpaque(true);

        btnIncTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnIncTr.setForeground(new java.awt.Color(255, 255, 255));
        btnIncTr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnIncrease.png"))); // NOI18N
        btnIncTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncTrMouseClicked(evt);
            }
        });

        jLabel45.setBackground(new java.awt.Color(113, 132, 137));
        jLabel45.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel45.setText("Trainee");
        jLabel45.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel45.setOpaque(true);

        lblSTr.setBackground(new java.awt.Color(113, 132, 137));
        lblSTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblSTr.setForeground(new java.awt.Color(255, 255, 255));
        lblSTr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSTr.setText(" ");
        lblSTr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblSTr.setOpaque(true);

        btnDecTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        btnDecTr.setForeground(new java.awt.Color(255, 255, 255));
        btnDecTr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnDecrease.png"))); // NOI18N
        btnDecTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecTrMouseClicked(evt);
            }
        });

        lblTTr.setBackground(new java.awt.Color(113, 132, 137));
        lblTTr.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblTTr.setForeground(new java.awt.Color(255, 255, 255));
        lblTTr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTTr.setText(" ");
        lblTTr.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblTTr.setOpaque(true);

        lblQTotal.setBackground(new java.awt.Color(113, 132, 137));
        lblQTotal.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblQTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQTotal.setText(" ");
        lblQTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQTotal.setOpaque(true);

        lblTTotal.setBackground(new java.awt.Color(113, 132, 137));
        lblTTotal.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblTTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTTotal.setText(" ");
        lblTTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblTTotal.setOpaque(true);

        jLabel51.setBackground(new java.awt.Color(113, 132, 137));
        jLabel51.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel51.setText("Total");
        jLabel51.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel51.setOpaque(true);

        lblHTotal.setBackground(new java.awt.Color(113, 132, 137));
        lblHTotal.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblHTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblHTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHTotal.setText(" ");
        lblHTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblHTotal.setOpaque(true);

        lblRTotal.setBackground(new java.awt.Color(113, 132, 137));
        lblRTotal.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblRTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblRTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRTotal.setText(" ");
        lblRTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblRTotal.setOpaque(true);

        btnCancel.setBackground(new java.awt.Color(113, 132, 137));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        btnCancel.setOpaque(true);

        btnAccept.setBackground(new java.awt.Color(113, 132, 137));
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accept.png"))); // NOI18N
        btnAccept.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        btnAccept.setOpaque(true);

        jLabel57.setBackground(new java.awt.Color(113, 132, 137));
        jLabel57.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel57.setText("Maximum");
        jLabel57.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        jLabel57.setOpaque(true);

        lblQMax.setBackground(new java.awt.Color(113, 132, 137));
        lblQMax.setFont(new java.awt.Font("Formula1 Display Regular", 0, 16)); // NOI18N
        lblQMax.setForeground(new java.awt.Color(255, 255, 255));
        lblQMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQMax.setText(" ");
        lblQMax.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 4, 5));
        lblQMax.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDecEx)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncEx)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQEx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHEx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblREx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSEx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTEx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDecVG)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncVG)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQVG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHVG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRVG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSVG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTVG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDecGd)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncGd)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQGd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHGd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRGd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSGd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTGd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDecAv)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncAv)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQAv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHAv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRAv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSAv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTAv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDecTr)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncTr)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQTr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHTr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRTr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSTr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTTr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblQTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(lblTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(lblQMax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAccept)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblREx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTEx)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTVG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncGd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecGd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQGd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHGd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRGd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSGd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTGd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTAv)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncTr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecTr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQTr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHTr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRTr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSTr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTTr)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQTotal)
                            .addComponent(lblHTotal)
                            .addComponent(lblRTotal)
                            .addComponent(lblTTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQMax)))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccept, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecExMouseClicked
        if (staff[0] > 0) {
            staff[0]--;
            hire[0]++;
            if (staff[0] < startStaff[0]) {
                redundancy[0]++;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnDecExMouseClicked

    private void btnDecVGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecVGMouseClicked
        if (staff[1] > 0) {
            staff[1]--;
            hire[1]++;
            if (staff[1] < startStaff[1]) {
                redundancy[1]++;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnDecVGMouseClicked

    private void btnDecGdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecGdMouseClicked
        if (staff[2] > 0) {
            staff[2]--;
            hire[2]++;
            if (staff[2] < startStaff[2]) {
                redundancy[2]++;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnDecGdMouseClicked

    private void btnDecAvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecAvMouseClicked
        if (staff[3] > 0) {
            staff[3]--;
            hire[3]++;
            if (staff[3] < startStaff[3]) {
                redundancy[3]++;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnDecAvMouseClicked

    private void btnDecTrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecTrMouseClicked
        if (staff[4] > 0) {
            staff[4]--;
            hire[4]++;
            if (staff[4] < startStaff[4]) {
                redundancy[4]++;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnDecTrMouseClicked

    private void btnIncExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncExMouseClicked
        if (staff[0] + staff[1] + staff[2] + staff[3] + staff[4] < maxStaff && hire[0] > 0) {
            staff[0]++;
            hire[0]--;
            if (redundancy[0] > 0) {
                redundancy[0]--;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnIncExMouseClicked

    private void btnIncVGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncVGMouseClicked
        if (staff[0] + staff[1] + staff[2] + staff[3] + staff[4] < maxStaff && hire[1] > 0) {
            staff[1]++;
            hire[1]--;
            if (redundancy[1] > 0) {
                redundancy[1]--;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnIncVGMouseClicked

    private void btnIncGdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncGdMouseClicked
        if (staff[0] + staff[1] + staff[2] + staff[3] + staff[4] < maxStaff && hire[2] > 0) {
            staff[2]++;
            hire[2]--;
            if (redundancy[2] > 0) {
                redundancy[2]--;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnIncGdMouseClicked

    private void btnIncAvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncAvMouseClicked
        if (staff[0] + staff[1] + staff[2] + staff[3] + staff[4] < maxStaff && hire[3] > 0) {
            staff[3]++;
            hire[3]--;
            if (redundancy[3] > 0) {
                redundancy[3]--;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnIncAvMouseClicked

    private void btnIncTrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncTrMouseClicked
        if (staff[0] + staff[1] + staff[2] + staff[3] + staff[4] < maxStaff && hire[4] > 0) {
            staff[4]++;
            hire[4]--;
            if (redundancy[4] > 0) {
                redundancy[4]--;
            }
        }
        updateScreenData();
    }//GEN-LAST:event_btnIncTrMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel btnAccept;
    protected javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnDecAv;
    private javax.swing.JLabel btnDecEx;
    private javax.swing.JLabel btnDecGd;
    private javax.swing.JLabel btnDecTr;
    private javax.swing.JLabel btnDecVG;
    private javax.swing.JLabel btnIncAv;
    private javax.swing.JLabel btnIncEx;
    private javax.swing.JLabel btnIncGd;
    private javax.swing.JLabel btnIncTr;
    private javax.swing.JLabel btnIncVG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHAv;
    private javax.swing.JLabel lblHEx;
    private javax.swing.JLabel lblHGd;
    private javax.swing.JLabel lblHTotal;
    private javax.swing.JLabel lblHTr;
    private javax.swing.JLabel lblHVG;
    private javax.swing.JLabel lblQAv;
    private javax.swing.JLabel lblQEx;
    private javax.swing.JLabel lblQGd;
    private javax.swing.JLabel lblQMax;
    private javax.swing.JLabel lblQTotal;
    private javax.swing.JLabel lblQTr;
    private javax.swing.JLabel lblQVG;
    private javax.swing.JLabel lblRAv;
    private javax.swing.JLabel lblREx;
    private javax.swing.JLabel lblRGd;
    private javax.swing.JLabel lblRTotal;
    private javax.swing.JLabel lblRTr;
    private javax.swing.JLabel lblRVG;
    private javax.swing.JLabel lblSAv;
    private javax.swing.JLabel lblSEx;
    private javax.swing.JLabel lblSGd;
    private javax.swing.JLabel lblSTr;
    private javax.swing.JLabel lblSVG;
    private javax.swing.JLabel lblTAv;
    private javax.swing.JLabel lblTEx;
    private javax.swing.JLabel lblTGd;
    private javax.swing.JLabel lblTTotal;
    private javax.swing.JLabel lblTTr;
    private javax.swing.JLabel lblTVG;
    // End of variables declaration//GEN-END:variables
}
